### ISSUE TITLE
Unable to compile the '  PsychicHTTP Server Example' included with the library (Arduino IDE)

### ISSUE THREAD

**Issue by SteveWeingart** [hoeken/PsychicHttp#166] opened 2024-08-14 13:50 UTC
HI,

Been going in circles for quite a while, I first tried to swap Psychic into a working system, but I was having a bunch of issues, so I decided to back off and start with the example included with the library and go forward.  But the Example won't compile.  Whether I set it for HTTPS or not, the compiler always includes this error:

C:\Users\steve\AppData\Local\Temp\arduino\sketches\858DD23424891439F0011B8F949E2EAC\sketch\Psychtest.ino.cpp.o: in function _GLOBAL__sub_D_ssid': C:\Users\steve\Documents\Arduino\Psychtest/Psychtest.ino:64: undefined reference to `PsychicHttpsServer::~PsychicHttpsServer()' collect2.exe: error: ld returned 1 exit status

My zipped code and the error codes are in  https://github.com/SteveWeingart/Psychictest 

I've completely scrubbed my environment, reinstalled Arduino IDE (both 1.8.19, and 2.3.2), and only the libraries I need for the project (the PsychicHttp, it's dependencies, and ESP-Flexystepper).

I believe that my setup is good, so this seems like a relatively important thing for anyone using the Arduino IDE.

Any help  very much appreciated.  I will continue to try and sort it out.

**Comment by DMSimone** [comment] 2024-08-14 13:56
FYI This is a duplicate of issue #163

**Closed** 2024-08-14 14:00 UTC
