### ISSUE TITLE
Is there a request timeout set method somewhere?

### ISSUE THREAD

**Issue by zekageri** [hoeken/PsychicHttp#23] opened 2023-12-12 13:08 UTC
In Async server when i had to defer a request because of a long operation i first set the rxTimeout and pass the request object to a class to process it. I would do the same in here because right now this is not working

```cpp
esp_err_t HardwareHandler::faultDelete(PsychicRequest *request) {
    if (!request->hasParam("id") || !request->hasParam("address") || !request->hasParam("serial")) {
        return request->reply(400);
    }
    // request->client()->setRxTimeout(30); // Set the timeout of the request to 30 second.
    int address = request->getParam("address")->value().toInt();
    Module *module = hwConfig.getModule(address);
    if (!module) { return request->reply(400); }
    module->faultdelete(request); // Pass the request object to an other class so it can process in the loop.
    return OK;
}
```

When the module class has finished processing the request it will reply with either 200 or 500.

**Comment by zekageri** [comment] 2023-12-12 13:17
In fact, none of my deferred requests are working now.

**Comment by hoeken** [comment] 2023-12-12 17:57
Okay, I was afraid of something like this when you mentioned deferred requests.

As it is right now, I don't think its really feasible to do that with PsychicHttp.  The ESP-IDF http server that its based on, expects the callback to handle the request and send its response entirely within that callback function.  I really don't know what happens if you try to use that request object outside the callback.

That being said, there are a couple possibilities:

1. It may be that you're not returning the right error code.  I see OK, and not ESP_OK.  If it sees anything other than ESP_OK, it will destroy the session.  That might be what's happening here.
2. Update your client side code to poll a status page to find out if the operation has completed
3. Have that page handle all the processing.  Unfortunately this will block the server from processing all responses.

Re: 3, the server is only partially asynchronous.  The whole thing runs in its own thread, but it only processes 1 request at a time in that thread.  However, in ESP-IDF 5.1.x they have added support to the http server so that its possible each request can be processed in its own thread.  Then you could certainly block and wait in a thread and other requests get processed fine.  The only problem is that the Arduino framework uses an older ESP-IDF 4.4.6 which doesn't have this feature.  The next Arduino version is in alpha right now, so hopefully it will be released soon.  Once its released, I would definitely like to add this feature as a truly asynchronous, multithreaded server is definitely the goal.

**Comment by zekageri** [comment] 2023-12-13 07:31
Well, that sucks. I have to rewrite a bunch of my request processing functions then.
`ESP_OK` and `OK` is the same thing. Both return 0. 
Does the server destroys the socket when the request is replyed or immidiately on return?
If it does not destroy it on return, it should be doable.

**Comment by hoeken** [comment] 2023-12-13 16:28
Okay I dug through the esp-idf stuff under the hood, and as long as you return ESP_OK it isn't destroying that socket.  So theoretically you *should* be able to process it outside that call.  There may be something I'm missing though as I'm only passingly familiar with the internals of the esp-idf server.

Could you simulate your call with curl?  ```curl -i -v -N``` specifically?  That would be enlightening.

It might be that you need to tell the client to keep the connection alive with the header ```Connection: keep-alive```.  The problem is that esp-idf stuff internally sends some basic headers including content-length when you send a response and the client might just be consuming that and moving on.  I'm a bit up against the limits of my knowledge here, sorry.

I think the best long-term route is probably just going to be implementing a poller.

**Comment by zekageri** [comment] 2023-12-13 17:05
Strange thing is that it is working sometimes. Not other times. Even with the same request. Curently iam sending back a response using events.

**Comment by hoeken** [comment] 2024-08-10 18:16
I'm closing all these old issues.  Please re-open it if needed.

**Closed by hoeken** 2024-08-10 18:16 UTC
